name: Build and Push with Buildah
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    env:
      HARBOR_URL: ${{ secrets.HARBOR_URL }}
      HARBOR_USERNAME: ${{ secrets.HARBOR_USERNAME }}
      HARBOR_API_TOKEN: ${{ secrets.HARBOR_API_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - run: |
          sudo apt-get update
          sudo apt-get install -y buildah

      - run: |
          echo "{\"auths\":{\"${HARBOR_URL}\":{\"username\":\"${HARBOR_USERNAME}\",\"password\":\"${HARBOR_API_TOKEN}\"}}}" > ~/.docker/config.json

      - name: buildah build
        run: buildah bud --format docker -t ${HARBOR_URL}/steveyiyo/ldap-portal:latest .

      - name: buildah push
        run: buildah push --creds "$HARBOR_USERNAME:$HARBOR_API_TOKEN" docker://$HARBOR_URL/steveyiyo/ldap-portal:latest
