name: Docker image build

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: self-hosted
    steps:
      - name: Install WireGuard
        run: |
          sudo apt-get update
          sudo apt-get install -y wireguard-tools

      - name: Bring up WireGuard
        run: |
          echo "${{ secrets.WG_CONFIG }}" > wg0.conf
          sudo chmod 600 wg0.conf
          sudo wg-quick up wg0

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Harbor
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.HARBOR_URL }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_API_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2.10.0
        with:
          context: .
          push: true
          tags: ${{ secrets.HARBOR_URL }}/steveyiyo/ldap-portal:latest
